apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    name: redis
    app: redis
spec:
  replicas: 1
  template:
    metadata:
      name: redis-master
      labels:
        name: redis-master
        app: redis
        role: master
        tier: backend
    spec:
      containers:
        - name: master
          image: redis
          ports:
            - containerPort: 6379
  selector:
    matchLabels:
        app: redis
        role: master
        tier: backend
