apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
    app: redis
    role: master
    tier: backend
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
        name: redis-pod
        app: redis
        role: master
        tier: backend
